#!/bin/bash

# This script configures Raspberry Pi 5 running OpenWrt as a Wi-Fi AP
# WAN: eth0 (school internet)
# LAN: wlan0 (creates your own subnet 192.168.50.0/24)
# NAT masquerading enabled so all clients are hidden behind the Pi

set -e

echo "[*] Configuring network interfaces..."

uci batch <<EOF
# Set WAN on eth0
set network.wan=interface
set network.wan.device='eth0'
set network.wan.proto='dhcp'

# Set LAN on wlan0
set network.lan=interface
set network.lan.device='wlan0'
set network.lan.proto='static'
set network.lan.ipaddr='192.168.50.1'
set network.lan.netmask='255.255.255.0'
set network.lan.ip6assign='60'
EOF

uci commit network
/etc/init.d/network restart

echo "[*] Configuring DHCP server for LAN..."

uci batch <<EOF
set dhcp.lan=dhcp
set dhcp.lan.interface='lan'
set dhcp.lan.start='100'
set dhcp.lan.limit='150'
set dhcp.lan.leasetime='12h'
EOF

uci commit dhcp
/etc/init.d/dnsmasq restart

echo "[*] Configuring wireless access point..."

uci batch <<EOF
set wireless.radio0=wifi-device
set wireless.radio0.type='mac80211'
set wireless.radio0.path='$(ls /sys/class/ieee80211/ | head -n1)'   # auto-detect first radio
set wireless.radio0.channel='6'
set wireless.radio0.htmode='HT20'

set wireless.default_radio0=wifi-iface
set wireless.default_radio0.device='radio0'
set wireless.default_radio0.mode='ap'
set wireless.default_radio0.network='lan'
set wireless.default_radio0.ssid='MyPi_AP'
set wireless.default_radio0.encryption='psk2'
set wireless.default_radio0.key='MyStrongPassword'
EOF

uci commit wireless
wifi reload

echo "[*] Enabling firewall rules with NAT masquerading..."

uci batch <<EOF
# LAN zone
set firewall.lan=zone
set firewall.lan.name='lan'
set firewall.lan.network='lan'
set firewall.lan.input='ACCEPT'
set firewall.lan.output='ACCEPT'
set firewall.lan.forward='ACCEPT'

# WAN zone with masquerading
set firewall.wan=zone
set firewall.wan.name='wan'
set firewall.wan.network='wan'
set firewall.wan.input='REJECT'
set firewall.wan.output='ACCEPT'
set firewall.wan.forward='REJECT'
set firewall.wan.masq='1'
set firewall.wan.mtu_fix='1'

# Forward LAN -> WAN
set firewall.lan_wan=forwarding
set firewall.lan_wan.src='lan'
set firewall.lan_wan.dest='wan'
EOF

uci commit firewall
/etc/init.d/firewall restart

echo "[+] Setup complete!"
echo "    Connect to Wi-Fi SSID: MyPi_AP"
echo "    Password: MyStrongPassword"
echo "    NAT enabled: school only sees the Pi, not your devices."
